import '../../domain/entities/product.dart';
import 'vietnamese_text_helper.dart';

/// Item in the curated sample images catalog.
class SampleImageCategory {
  final String id;
  final String industry;
  final String name;
  final String imageUrl;
  final List<String> keywords;
  final List<String> negativeKeywords;
  final int priority;

  const SampleImageCategory({
    required this.id,
    required this.industry,
    required this.name,
    required this.imageUrl,
    required this.keywords,
    this.negativeKeywords = const [],
    this.priority = 0,
  });
}

/// Match result containing the category and calculated relevance score.
class SampleImageMatch {
  final SampleImageCategory category;
  final int score;

  const SampleImageMatch({
    required this.category,
    required this.score,
  });

  String get id => category.id;
  String get industry => category.industry;
  String get name => category.name;
  String get imageUrl => category.imageUrl;
}

/// Smart sample image catalog specialized 100% for Furniture & Home Woodcraft
/// categorized across 6 room spaces.
class SampleImageHelper {
  static const String universalPlaceholderUrl =
      'https://images.unsplash.com/photo-1586769852044-692d6e3703f0?w=600&auto=format&fit=crop&q=80';

  static const List<String> roomOrder = [
    'Phòng khách',
    'Phòng ngủ',
    'Phòng ăn & Bếp',
    'Phòng làm việc',
    'Phòng thờ',
    'Sân vườn / Ngoài trời',
  ];

  static List<String> get industries => roomOrder;

  /// 100% Curated Furniture & Home Woodcraft Catalog across 6 Room Spaces
  static final List<SampleImageCategory> catalog = [
    const SampleImageCategory(
      id: 'living_sofa_straight',
      industry: 'Phòng khách',
      name: 'Sofa văng',
      imageUrl:
          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'sofa vang',
        'sofa văng',
        'sofa bang',
        'sofa băng',
        'ghe sofa vang',
        'ghế sofa văng',
        'sofa 2 cho',
        'sofa 2 chỗ',
        'sofa 3 cho',
        'sofa 3 chỗ',
        'sofa don dai',
        'sofa đôn dài',
      ],
      negativeKeywords: [
        'sofa l',
        'sofa goc',
        'sofa góc',
        'sofa bed',
        'sofa giuong',
        'sofa giường'
      ],
      priority: 22,
    ),
    const SampleImageCategory(
      id: 'furniture_sofas_living',
      industry: 'Phòng khách',
      name: 'Sofa nỉ góc chữ L & Sofa da, Sofa bed',
      imageUrl:
          'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'sofa da goc l',
        'sofa da góc l',
        'sofa da',
        'sofa ni nhung',
        'sofa nỉ nhung',
        'sofa ni phong khach',
        'sofa nỉ phòng khách',
        'sofa ni',
        'sofa nỉ',
        'ghe sofa bed',
        'ghế sofa bed',
        'sofa bed',
        'sofa giuong',
        'sofa giường',
        'sofa goc l',
        'sofa góc l',
        'sofa l',
        'sofa goc chu l',
        'sofa góc chữ l',
        'sofa goc',
        'sofa góc',
        'sofa ni goc',
        'sofa nỉ góc',
        'ghe sofa',
        'ghế sofa',
        'bo sofa',
        'bộ sofa',
        'sofa phong khach',
        'sofa phòng khách',
        'sofa',
      ],
      negativeKeywords: [
        'bot giat',
        'bột giặt',
        'nuoc giat',
        'nước giặt',
        'nuoc xa',
        'nước xả',
      ],
      priority: 35,
    ),
    const SampleImageCategory(
      id: 'living_sofa_bed',
      industry: 'Phòng khách',
      name: 'Sofa giường thông minh',
      imageUrl:
          'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'sofa giuong',
        'sofa giường',
        'sofa bed',
        'sofa thong minh',
        'sofa thông minh',
        'giuong sofa',
        'giường sofa',
        'sofa gap',
        'sofa gấp',
      ],
      priority: 24,
    ),
    const SampleImageCategory(
      id: 'living_armchair',
      industry: 'Phòng khách',
      name: 'Ghế bành đơn',
      imageUrl:
          'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ghe banh',
        'ghế bành',
        'ghe banh don',
        'ghế bành đơn',
        'ghe don sofa',
        'ghế đơn sofa',
        'armchair',
        'ghe thu gian phong khach',
        'ghế thư giãn phòng khách',
      ],
      negativeKeywords: ['ghe xoay', 'ghế xoay', 'ghe gaming', 'ghế gaming'],
      priority: 20,
    ),
    const SampleImageCategory(
      id: 'living_tea_table_stone',
      industry: 'Phòng khách',
      name: 'Bàn trà đôi mặt đá',
      imageUrl:
          'https://images.unsplash.com/photo-1533090161767-e6ffed986b88?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ban tra doi',
        'bàn trà đôi',
        'ban tra mat da',
        'bàn trà mặt đá',
        'ban tra doi mat da',
        'bàn trà đôi mặt đá',
        'ban sofa mat da',
        'bàn sofa mặt đá',
      ],
      negativeKeywords: ['ban an', 'bàn ăn'],
      priority: 24,
    ),
    const SampleImageCategory(
      id: 'living_sofa_table_glass',
      industry: 'Phòng khách',
      name: 'Bàn sofa mặt kính',
      imageUrl:
          'https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ban sofa mat kinh',
        'bàn sofa mặt kính',
        'ban tra mat kinh',
        'bàn trà mặt kính',
        'ban kinh sofa',
        'bàn kính sofa',
        'ban sofa',
        'bàn sofa',
        'ban tra',
        'bàn trà',
      ],
      negativeKeywords: ['ban an', 'bàn ăn'],
      priority: 22,
    ),
    const SampleImageCategory(
      id: 'living_tea_table_wood',
      industry: 'Phòng khách',
      name: 'Bàn trà tròn gỗ',
      imageUrl:
          'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ban tra tron',
        'bàn trà tròn',
        'ban tra go',
        'bàn trà gỗ',
        'ban tra tron go',
        'bàn trà tròn gỗ',
        'ban sofa go',
        'bàn sofa gỗ',
      ],
      negativeKeywords: ['ban an', 'bàn ăn'],
      priority: 22,
    ),
    const SampleImageCategory(
      id: 'living_tv_stand_stone',
      industry: 'Phòng khách',
      name: 'Kệ Tivi mặt đá',
      imageUrl:
          'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ke tivi mat da',
        'kệ tivi mặt đá',
        'ke tv mat da',
        'kệ tv mặt đá',
        'ke tivi da',
        'kệ tivi đá',
        'ke tv da',
      ],
      priority: 24,
    ),
    const SampleImageCategory(
      id: 'living_tv_stand_wood',
      industry: 'Phòng khách',
      name: 'Kệ tivi gỗ rút 2 đầu',
      imageUrl:
          'https://images.unsplash.com/photo-1600488999129-e49592bd2111?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ke tv',
        'kệ tv',
        'ke tivi',
        'kệ tivi',
        'ke tivi go',
        'kệ tivi gỗ',
        'ke tivi rut 2 dau',
        'kệ tivi rút 2 đầu',
        'ke tv go',
        'kệ tv gỗ',
        'ke tivi go phong khach',
        'kệ tivi gỗ phòng khách',
      ],
      negativeKeywords: ['mat da', 'mặt đá'],
      priority: 22,
    ),
    const SampleImageCategory(
      id: 'living_wine_cabinet',
      industry: 'Phòng khách',
      name: 'Tủ rượu phòng khách',
      imageUrl:
          'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'tu ruou',
        'tủ rượu',
        'tu ruou phong khach',
        'tủ rượu phòng khách',
        'tu trung bay ruou',
        'tủ trưng bày rượu',
        'tu ruou go',
        'tủ rượu gỗ',
      ],
      priority: 20,
    ),
    const SampleImageCategory(
      id: 'living_truong_ky_gu',
      industry: 'Phòng khách',
      name: 'Trường kỷ gỗ gụ',
      imageUrl:
          'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'truong ky',
        'trường kỷ',
        'truong ky go gu',
        'trường kỷ gỗ gụ',
        'truong ky go',
        'trường kỷ gỗ',
        'bo truong ky',
        'bộ trường kỷ',
      ],
      negativeKeywords: [
        'can oc',
        'cẩn ốc',
        'xa cu',
        'xà cừ',
        'kham oc',
        'khảm ốc'
      ],
      priority: 25,
    ),
    const SampleImageCategory(
      id: 'living_truong_ky_xa_cu',
      industry: 'Phòng khách',
      name: 'Trường kỷ cẩn ốc xà cừ',
      imageUrl:
          'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'truong ky can oc',
        'trường kỷ cẩn ốc',
        'can oc xa cu',
        'cẩn ốc xà cừ',
        'truong ky kham oc',
        'trường kỷ khảm ốc',
        'can oc',
        'cẩn ốc',
        'kham oc',
        'khảm ốc',
      ],
      priority: 26,
    ),
    const SampleImageCategory(
      id: 'living_salon_wood',
      industry: 'Phòng khách',
      name: 'Bộ sa lông gỗ truyền thống',
      imageUrl:
          'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'sa long go',
        'sa lông gỗ',
        'bo sa long',
        'bộ sa lông',
        'salon go',
        'salon gỗ',
        'bo ban ghe go phong khach',
        'bộ bàn ghế gỗ phòng khách',
        'ban ghe phong khach',
        'bàn ghế phòng khách',
      ],
      priority: 20,
    ),
    const SampleImageCategory(
      id: 'home_bedding_mattress',
      industry: 'Phòng ngủ',
      name: 'Giường ngủ gỗ tự nhiên (gỗ sồi, gõ đỏ) & Nệm, Ga gối',
      imageUrl:
          'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'giuong ngu go soi',
        'giường ngủ gỗ sồi',
        'giuong ngu 1m8',
        'giường ngủ 1m8',
        'giuong 1m8',
        'giường 1m8',
        'giuong 1m6',
        'giường 1m6',
        'giuong 2m',
        'giường 2m',
        'giuong ngu go',
        'giường ngủ gỗ',
        'giuong go soi',
        'giường gỗ sồi',
        'giuong go go do',
        'giường gỗ gõ đỏ',
        'giuong go tu nhien',
        'giường gỗ tự nhiên',
        'giuong ngu',
        'giường ngủ',
        'giuong go',
        'giường gỗ',
        'giuong',
        'giường',
        'nem cao su non',
        'nệm cao su non',
        'nem cao su',
        'nệm cao su',
        'nem',
        'nệm',
        'goi om cao su',
        'gối ôm cao su',
        'goi om',
        'gối ôm',
        'chan he tencel',
        'chăn hè tencel',
        'chan he',
        'chăn hè',
        'chan ga goi dem',
        'chăn ga gối đệm',
        'chan ga',
        'chăn ga',
        'dem',
        'đệm',
        'ruot goi',
        'ruột gối',
        'vo goi',
        'vỏ gối',
        'goi dau',
        'gối đầu',
        'goi nam',
        'gối nằm',
        'chan',
        'chăn',
      ],
      negativeKeywords: [
        'bánh mì',
        'banh mi',
        'ăn dặm',
        'an dam',
        'sofa giuong',
        'sofa giường',
        'giuong tang',
        'giường tầng',
        'dầu gội',
        'dau goi',
        'dầu xả',
        'dau xa',
        'sữa tắm',
        'sua tam',
        'mì gói',
        'mi goi',
        'gói mì',
        'goi mi',
      ],
      priority: 35,
    ),
    const SampleImageCategory(
      id: 'bedroom_bed_upholstered',
      industry: 'Phòng ngủ',
      name: 'Giường bọc nệm hiện đại',
      imageUrl:
          'https://images.unsplash.com/photo-1540518614846-7ede433c4570?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'giuong boc nem',
        'giường bọc nệm',
        'giuong boc da',
        'giường bọc da',
        'giuong boc vai',
        'giường bọc vải',
        'giuong ngu hien dai',
        'giường ngủ hiện đại',
      ],
      priority: 22,
    ),
    const SampleImageCategory(
      id: 'bedroom_bed_storage',
      industry: 'Phòng ngủ',
      name: 'Giường thông minh có ngăn kéo',
      imageUrl:
          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'giuong co ngan keo',
        'giường có ngăn kéo',
        'giuong thong minh',
        'giường thông minh',
        'giuong hop',
        'giường hộp',
      ],
      priority: 22,
    ),
    const SampleImageCategory(
      id: 'bedroom_bunk_bed',
      industry: 'Phòng ngủ',
      name: 'Giường tầng',
      imageUrl:
          'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'giuong tang',
        'giường tầng',
        'giuong tang tre em',
        'giường tầng trẻ em',
        'giuong 2 tang',
        'giường 2 tầng',
      ],
      priority: 24,
    ),
    const SampleImageCategory(
      id: 'bedroom_mattress_natural_latex',
      industry: 'Phòng ngủ',
      name: 'Nệm cao su thiên nhiên',
      imageUrl:
          'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'nem cao su thien nhien',
        'nệm cao su thiên nhiên',
        'dem cao su thien nhien',
        'đệm cao su thiên nhiên',
        'nem kymdan',
        'nệm kymdan',
        'nem van thanh',
        'nệm vạn thành',
        'nem lien a',
        'nệm liên á',
      ],
      negativeKeywords: ['cao su non'],
      priority: 25,
    ),
    const SampleImageCategory(
      id: 'bedroom_mattress_memory_foam',
      industry: 'Phòng ngủ',
      name: 'Nệm cao su non',
      imageUrl:
          'https://images.unsplash.com/photo-1629949009765-40fc74c95018?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'nem cao su non',
        'nệm cao su non',
        'dem cao su non',
        'đệm cao su non',
        'nem foam',
        'nệm foam',
      ],
      negativeKeywords: [
        'nem cao su thien nhien',
        'nệm cao su thiên nhiên',
        'kymdan'
      ],
      priority: 25,
    ),
    const SampleImageCategory(
      id: 'bedroom_mattress_spring',
      industry: 'Phòng ngủ',
      name: 'Nệm lò xo túi',
      imageUrl:
          'https://images.unsplash.com/photo-1582533561751-ef6f6ab93a2e?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'nem lo xo',
        'nệm lò xo',
        'nem lo xo tui',
        'nệm lò xo túi',
        'dem lo xo',
        'đệm lò xo',
        'nem lo xo lien ket',
        'nệm lò xo liên kết',
      ],
      priority: 24,
    ),
    const SampleImageCategory(
      id: 'bedroom_mattress_cotton_fold',
      industry: 'Phòng ngủ',
      name: 'Nệm bông ép gấp 3',
      imageUrl:
          'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'nem bong ep',
        'nệm bông ép',
        'nem gap 3',
        'nệm gấp 3',
        'dem bong ep',
        'đệm bông ép',
        'nem hanvico',
        'nệm hanvico',
      ],
      priority: 22,
    ),
    const SampleImageCategory(
      id: 'bedroom_bedding_set',
      industry: 'Phòng ngủ',
      name: 'Chăn ga gối đệm nỉ nhung, Cotton Tencel',
      imageUrl:
          'https://images.unsplash.com/photo-1616046229478-9901c5536a45?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'chan ga',
        'chăn ga',
        'chan ga goi',
        'chăn ga gối',
        'cotton tencel',
        'ni nhung',
        'nỉ nhung',
        'drap giuong',
        'drap giường',
        'vo goi',
        'vỏ gối',
        'ruot goi',
        'ruột gối',
        'chan he',
        'chăn hè',
        'goi om',
        'gối ôm',
        'goi cao su',
        'gối cao su',
      ],
      negativeKeywords: [
        'mi goi',
        'mì gói',
        'goi mi',
        'gói mì',
        'mi tom',
        'mì tôm',
        'banh',
        'bánh'
      ],
      priority: 20,
    ),
    const SampleImageCategory(
      id: 'bedroom_wardrobe_sliding',
      industry: 'Phòng ngủ',
      name: 'Tủ quần áo cánh lùa',
      imageUrl:
          'https://images.unsplash.com/photo-1558997519-83ea9252def8?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'tu quan ao canh lua',
        'tủ quần áo cánh lùa',
        'tu canh lua',
        'tủ cánh lùa',
        'tu ao canh truot',
        'tủ áo cánh trượt',
      ],
      priority: 24,
    ),
    const SampleImageCategory(
      id: 'furniture_wardrobes_shelves',
      industry: 'Phòng ngủ',
      name: 'Tủ gỗ 3-4 cánh & Kệ tivi, Tủ đầu giường, Kệ sắt',
      imageUrl:
          'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'tu quan ao go mdf 4 canh',
        'tủ quần áo gỗ mdf 4 cánh',
        'tu quan ao 4 canh',
        'tủ quần áo 4 cánh',
        'tu quan ao go',
        'tủ quần áo gỗ',
        'tu quan ao',
        'tủ quần áo',
        'tu ao',
        'tủ áo',
        'tu go 3-4 canh',
        'tủ gỗ 3-4 cánh',
        'tu go 3 canh',
        'tủ gỗ 3 cánh',
        'tu go 4 canh',
        'tủ gỗ 4 cánh',
        'ke sach mini de ban',
        'kệ sách mini để bàn',
        'ke sach mini',
        'kệ sách mini',
        'ke sach',
        'kệ sách',
        'gia sach',
        'giá sách',
        'ke tivi phong khach rut 2 dau',
        'kệ tivi phòng khách rút 2 đầu',
        'ke tivi phong khach',
        'kệ tivi phòng khách',
        'ke tivi rut 2 dau',
        'kệ tivi rút 2 đầu',
        'ke tivi',
        'kệ tivi',
        'tu dau giuong 2 ngan keo',
        'tủ đầu giường 2 ngăn kéo',
        'tu dau giuong',
        'tủ đầu giường',
        'tab dau giuong',
        'tab đầu giường',
        'ke sat da nang 5 tang',
        'kệ sắt đa năng 5 tầng',
        'ke sat da nang',
        'kệ sắt đa năng',
        'ke sat',
        'kệ sắt',
        'tu giay',
        'tủ giày',
        'ke giay',
        'kệ giày',
        'tu ho so',
        'tủ hồ sơ',
        'tu dung do',
        'tủ đựng đồ',
        'ke trang tri',
        'kệ trang trí',
      ],
      negativeKeywords: [
        'tủ lạnh',
        'tu lanh',
        'túi',
        'tui',
        'tủ đông',
        'tu dong',
        'kệ chén',
        'ke chen',
        'mat da',
        'mặt đá',
        'treo tuong',
        'treo tường',
        'chu u',
        'chữ u',
      ],
      priority: 35,
    ),
    const SampleImageCategory(
      id: 'bedroom_wardrobe_aluminum_glass',
      industry: 'Phòng ngủ',
      name: 'Tủ nhôm kính',
      imageUrl:
          'https://images.unsplash.com/photo-1595514535415-dae45318536f?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'tu nhom kinh',
        'tủ nhôm kính',
        'tu quan ao nhom kinh',
        'tủ quần áo nhôm kính',
        'tu ao nhom kinh',
      ],
      negativeKeywords: ['tu bep', 'tủ bếp', 'tu chen', 'tủ chén'],
      priority: 20,
    ),
    const SampleImageCategory(
      id: 'bedroom_dressing_table_led',
      industry: 'Phòng ngủ',
      name: 'Bàn trang điểm / Bàn phấn có gương đèn LED',
      imageUrl:
          'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ban trang diem',
        'bàn trang điểm',
        'ban phan',
        'bàn phấn',
        'guong den led',
        'gương đèn led',
        'ban trang diem den led',
        'bàn trang điểm đèn led',
      ],
      priority: 24,
    ),
    const SampleImageCategory(
      id: 'bedroom_vanity_chair',
      industry: 'Phòng ngủ',
      name: 'Ghế nơ trang điểm',
      imageUrl:
          'https://images.unsplash.com/photo-1506898667547-42e22a46e125?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ghe no',
        'ghế nơ',
        'ghe no trang diem',
        'ghế nơ trang điểm',
        'ghe trang diem',
        'ghế trang điểm',
        'ghe ban phan',
        'ghế bàn phấn',
      ],
      priority: 22,
    ),
    const SampleImageCategory(
      id: 'bedroom_nightstand',
      industry: 'Phòng ngủ',
      name: 'Tủ đầu giường (Tab đầu giường) gỗ và da',
      imageUrl:
          'https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'tu dau giuong',
        'tủ đầu giường',
        'tab dau giuong',
        'tab đầu giường',
        'tap dau giuong',
        'táp đầu giường',
        'don dau giuong',
        'đôn đầu giường',
      ],
      priority: 22,
    ),
    const SampleImageCategory(
      id: 'furniture_dining_living_tables',
      industry: 'Phòng ăn & Bếp',
      name: 'Bàn ăn mặt đá cẩm thạch chống xước & Bàn trà sofa, Bàn cafe',
      imageUrl:
          'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ban an 4 ghe mat da',
        'bàn ăn 4 ghế mặt đá',
        'ban an 4 ghe',
        'bàn ăn 4 ghế',
        'ban an 6 ghe',
        'bàn ăn 6 ghế',
        'bo ban an 6 ghe',
        'bộ bàn ăn 6 ghế',
        'ban an',
        'bàn ăn',
        'bo ban an',
        'bộ bàn ăn',
        'ban an mat da',
        'bàn ăn mặt đá',
        'ban an go tu nhien',
        'bàn ăn gỗ tự nhiên',
        'ban tra sofa phong khach',
        'bàn trà sofa phòng khách',
        'ban tra sofa',
        'bàn trà sofa',
        'ban sofa',
        'bàn sofa',
        'ban tra tron doi',
        'bàn trà tròn đôi',
        'ban tra tron',
        'bàn trà tròn',
        'ban tra',
        'bàn trà',
        'ban cafe chan sat',
        'bàn cafe chân sắt',
        'ban cafe',
        'bàn cafe',
        'ban ca phe',
        'bàn cà phê',
        'ban tron',
        'bàn tròn',
        'ban mat da',
        'bàn mặt đá',
        'ban tiep khach',
        'bàn tiếp khách',
      ],
      negativeKeywords: [
        'bàn làm việc',
        'ban lam viec',
        'bàn gaming',
        'ban gaming',
        'bàn phím',
        'ban phim',
        'bàn ủi',
        'ban ui',
        'bàn là',
        'ban la',
        'bàn chải',
        'ban chai',
        'khăn trải bàn',
        'khan trai ban',
        'ke sach',
        'kệ sách',
      ],
      priority: 35,
    ),
    const SampleImageCategory(
      id: 'dining_table_natural_wood',
      industry: 'Phòng ăn & Bếp',
      name: 'Bàn ăn gỗ tự nhiên',
      imageUrl:
          'https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ban an go',
        'bàn ăn gỗ',
        'ban an go tu nhien',
        'bàn ăn gỗ tự nhiên',
        'ban an go soi',
        'bàn ăn gỗ sồi',
      ],
      negativeKeywords: ['ban lam viec', 'bàn làm việc', 'ban hoc', 'bàn học'],
      priority: 24,
    ),
    const SampleImageCategory(
      id: 'dining_table_extendable',
      industry: 'Phòng ăn & Bếp',
      name: 'Bàn ăn thông minh xếp gọn kéo dài',
      imageUrl:
          'https://images.unsplash.com/photo-1577140917170-285929fb55b7?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ban an thong minh',
        'bàn ăn thông minh',
        'ban an xep gon',
        'bàn ăn xếp gọn',
        'ban an keo dai',
        'bàn ăn kéo dài',
        'ban an gap gon',
        'bàn ăn gấp gọn',
      ],
      priority: 23,
    ),
    const SampleImageCategory(
      id: 'dining_chair_leather',
      industry: 'Phòng ăn & Bếp',
      name: 'Ghế ăn bọc da cao cấp',
      imageUrl:
          'https://images.unsplash.com/photo-1503602642458-232111445657?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ghe an boc da',
        'ghế ăn bọc da',
        'ghe an da',
        'ghế ăn da',
        'ghe phong an',
        'ghế phòng ăn',
        'ghe an cao cap',
        'ghế ăn cao cấp',
      ],
      negativeKeywords: ['ghe xoay', 'ghế xoay', 'ghe gaming', 'ghế gaming'],
      priority: 22,
    ),
    const SampleImageCategory(
      id: 'dining_chair_wood',
      industry: 'Phòng ăn & Bếp',
      name: 'Ghế ăn gỗ Monet/Nelson',
      imageUrl:
          'https://images.unsplash.com/photo-1581539250439-c96689b516dd?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ghe an go',
        'ghế ăn gỗ',
        'ghe monet',
        'ghế monet',
        'ghe nelson',
        'ghế nelson',
        'ghe an',
        'ghế ăn',
      ],
      negativeKeywords: ['ghe xoay', 'ghế xoay', 'ghe gaming', 'ghế gaming'],
      priority: 21,
    ),
    const SampleImageCategory(
      id: 'kitchen_dish_cupboard',
      industry: 'Phòng ăn & Bếp',
      name: 'Tủ chén',
      imageUrl:
          'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'tu chen',
        'tủ chén',
        'tu bat dia',
        'tủ bát đĩa',
        'tu dung bat chen',
        'tủ đựng bát chén',
      ],
      priority: 22,
    ),
    const SampleImageCategory(
      id: 'kitchen_cabinet_aluminum',
      industry: 'Phòng ăn & Bếp',
      name: 'Tủ bếp nhôm kính',
      imageUrl:
          'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'tu bep',
        'tủ bếp',
        'tu bep nhom kinh',
        'tủ bếp nhôm kính',
        'ke bep',
        'kệ bếp',
        'tu bep treo tuong',
        'tủ bếp treo tường',
      ],
      priority: 22,
    ),
    const SampleImageCategory(
      id: 'kitchen_microwave_rack',
      industry: 'Phòng ăn & Bếp',
      name: 'Kệ để lò vi sóng và nồi chiên đa năng',
      imageUrl:
          'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ke de lo vi song',
        'kệ để lò vi sóng',
        'ke lo vi song',
        'kệ lò vi sóng',
        'ke de noi chien',
        'kệ để nồi chiên',
        'ke bep da nang',
        'kệ bếp đa năng',
      ],
      negativeKeywords: [
        'noi chien khong dau',
        'nồi chiên không dầu',
        'noi chien',
        'nồi chiên'
      ],
      priority: 20,
    ),
    const SampleImageCategory(
      id: 'kitchen_dish_rack_inox',
      industry: 'Phòng ăn & Bếp',
      name: 'Kệ chén bát inox',
      imageUrl:
          'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ke chen bat inox',
        'kệ chén bát inox',
        'ke chen inox',
        'kệ chén inox',
        'gia de bat dia inox',
        'giá để bát đĩa inox',
        'ke bat dia inox',
        'kệ bát đĩa inox',
      ],
      priority: 21,
    ),
    const SampleImageCategory(
      id: 'furniture_desks_work',
      industry: 'Phòng làm việc',
      name: 'Bàn làm việc chân sắt chữ K/Z/U & Gaming, Bàn học sinh',
      imageUrl:
          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ban chu k',
        'bàn chữ k',
        'ban k',
        'bàn k',
        'ban chu z gaming',
        'bàn chữ z gaming',
        'ban chu z',
        'bàn chữ z',
        'ban z',
        'bàn z',
        'ban gaming chu l',
        'bàn gaming chữ l',
        'ban gaming',
        'bàn gaming',
        'ban vi tinh van phong',
        'bàn vi tính văn phòng',
        'ban vi tinh',
        'bàn vi tính',
        'ban may tinh',
        'bàn máy tính',
        'ban hoc sinh chong gu',
        'bàn học sinh chống gù',
        'ban hoc sinh',
        'bàn học sinh',
        'ban hoc',
        'bàn học',
        'ban chu u',
        'bàn chữ u',
        'ban chan sat',
        'bàn chân sắt',
        'ban lam viec',
        'bàn làm việc',
        'ban van phong',
        'bàn văn phòng',
        'ban nang ha',
        'bàn nâng hạ',
      ],
      negativeKeywords: [
        'ban ui',
        'bàn ủi',
        'ban phim',
        'bàn phím',
        'ban an',
        'bàn ăn',
        'ban tra',
        'bàn trà',
        'ban sofa',
        'bàn sofa',
        'ban cafe',
        'bàn cafe',
        'ke sach',
        'kệ sách',
        'gia sach',
        'giá sách',
      ],
      priority: 35,
    ),
    const SampleImageCategory(
      id: 'office_desk_gaming_led',
      industry: 'Phòng làm việc',
      name: 'Bàn gaming LED',
      imageUrl:
          'https://images.unsplash.com/photo-1616588589676-62b3bd4ff6d2?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ban chu z gaming',
        'bàn chữ z gaming',
        'ban gaming',
        'bàn gaming',
        'ban gaming led',
        'bàn gaming led',
        'ban game',
        'bàn game',
      ],
      negativeKeywords: ['ban phim', 'bàn phím'],
      priority: 24,
    ),
    const SampleImageCategory(
      id: 'office_desk_study_bookshelf',
      industry: 'Phòng làm việc',
      name: 'Bàn học sinh liền kệ sách',
      imageUrl:
          'https://images.unsplash.com/photo-1516962215378-7fa2e137ae93?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ban hoc sinh',
        'bàn học sinh',
        'ban hoc',
        'bàn học',
        'ban lien ke sach',
        'bàn liền kệ sách',
        'ban hoc co gia sach',
        'bàn học có giá sách',
        'ban tre em',
        'bàn trẻ em',
      ],
      priority: 24,
    ),
    const SampleImageCategory(
      id: 'office_desk_standing_adjustable',
      industry: 'Phòng làm việc',
      name: 'Bàn nâng hạ độ cao',
      imageUrl:
          'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ban nang ha',
        'bàn nâng hạ',
        'ban nang ha do cao',
        'bàn nâng hạ độ cao',
        'standing desk',
        'ban cong thai hoc',
        'bàn công thái học',
      ],
      priority: 23,
    ),
    const SampleImageCategory(
      id: 'office_chair_swivel_mesh',
      industry: 'Phòng làm việc',
      name: 'Ghế xoay văn phòng lưới thoáng khí',
      imageUrl:
          'https://images.unsplash.com/photo-1505797149-43b0069ec26b?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ghe xoay',
        'ghế xoay',
        'ghe xoay van phong',
        'ghế xoay văn phòng',
        'ghe luoi van phong',
        'ghế lưới văn phòng',
        'ghe lam viec',
        'ghế làm việc',
        'ghe van phong',
        'ghế văn phòng',
      ],
      negativeKeywords: ['ghe an', 'ghế ăn', 'ghe dot nhang', 'ghế đốt nhang'],
      priority: 24,
    ),
    const SampleImageCategory(
      id: 'furniture_chairs_ergonomic',
      industry: 'Phòng làm việc',
      name: 'Ghế xoay văn phòng lưới & Ghế công thái học, Gaming, Giám đốc',
      imageUrl:
          'https://images.unsplash.com/photo-1580481077197-2856230f8983?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ghe xoay van phong luoi',
        'ghế xoay văn phòng lưới',
        'ghe xoay van phong',
        'ghế xoay văn phòng',
        'ghe xoay luoi',
        'ghế xoay lưới',
        'ghe xoay',
        'ghế xoay',
        'ghe cong thai hoc sihoo',
        'ghế công thái học sihoo',
        'ghe cong thai hoc',
        'ghế công thái học',
        'ghe ergonomic',
        'ghế ergonomic',
        'sihoo',
        'ghe gaming e-dra',
        'ghế gaming e-dra',
        'ghe gaming',
        'ghế gaming',
        'ghe giam doc chan quy',
        'ghế giám đốc chân quỳ',
        'ghe giam doc',
        'ghế giám đốc',
        'ghe chan quy',
        'ghế chân quỳ',
        'ghe van phong',
        'ghế văn phòng',
        'ghe luoi',
        'ghế lưới',
        'ghe lam viec',
        'ghế làm việc',
        'ghe don',
        'ghế đôn',
        'ghe go',
        'ghế gỗ',
        'e-dra',
        'edra',
      ],
      negativeKeywords: [
        'ghế ăn dặm',
        'ghe an dam',
        'ghế massage',
        'ghe massage',
        'ghế sofa',
        'ghe sofa',
        'bàn ăn',
        'ban an',
        'ghe an',
        'ghế ăn',
        'ghe banh',
        'ghế bành',
        'ghe dot nhang',
        'ghế đốt nhang',
        'ghe thap huong',
        'ghế thắp hương',
      ],
      priority: 35,
    ),
    const SampleImageCategory(
      id: 'office_chair_executive_leather',
      industry: 'Phòng làm việc',
      name: 'Ghế giám đốc bọc da',
      imageUrl:
          'https://images.unsplash.com/photo-1589384267710-7a170981ca78?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ghe giam doc',
        'ghế giám đốc',
        'ghe da giam doc',
        'ghế da giám đốc',
        'ghe thu truong',
        'ghế thủ trưởng',
        'ghe da cao cap',
        'ghế da cao cấp',
      ],
      priority: 22,
    ),
    const SampleImageCategory(
      id: 'office_chair_gaming_cantilever',
      industry: 'Phòng làm việc',
      name: 'Ghế gaming chân quỳ',
      imageUrl:
          'https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ghe gaming',
        'ghế gaming',
        'ghe chan quy',
        'ghế chân quỳ',
        'ghe net',
        'ghế net',
        'ghe phong net',
        'ghế phòng net',
      ],
      priority: 23,
    ),
    const SampleImageCategory(
      id: 'office_bookshelf_standing_u',
      industry: 'Phòng làm việc',
      name: 'Kệ sách đứng chữ U',
      imageUrl:
          'https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ke sach',
        'kệ sách',
        'ke sach dung',
        'kệ sách đứng',
        'ke sach chu u',
        'kệ sách chữ u',
        'gia sach',
        'giá sách',
      ],
      negativeKeywords: ['ke tivi', 'kệ tivi', 'tu quan ao', 'tủ quần áo'],
      priority: 22,
    ),
    const SampleImageCategory(
      id: 'office_document_shelf',
      industry: 'Phòng làm việc',
      name: 'Kệ tài liệu văn phòng',
      imageUrl:
          'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ke tai lieu',
        'kệ tài liệu',
        'ke ho so',
        'kệ hồ sơ',
        'tu tai lieu',
        'tủ tài liệu',
        'tu ho so',
        'tủ hồ sơ',
      ],
      priority: 21,
    ),
    const SampleImageCategory(
      id: 'office_bookshelf_wall_hanging',
      industry: 'Phòng làm việc',
      name: 'Giá sách gỗ treo tường',
      imageUrl:
          'https://images.unsplash.com/photo-1532372576444-dda954194ad0?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'gia sach treo tuong',
        'giá sách treo tường',
        'ke sach treo tuong',
        'kệ sách treo tường',
        'ke go treo tuong',
        'kệ gỗ treo tường',
      ],
      priority: 21,
    ),
    const SampleImageCategory(
      id: 'altar_ancestral_cabinet',
      industry: 'Phòng thờ',
      name: 'Tủ thờ gia tiên gỗ gõ đỏ/gụ',
      imageUrl:
          'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'tu tho',
        'tủ thờ',
        'tu tho gia tien',
        'tủ thờ gia tiên',
        'tu tho go',
        'tủ thờ gỗ',
        'tu tho go go do',
        'tủ thờ gỗ gõ đỏ',
        'tu tho go gu',
        'tủ thờ gỗ gụ',
        'tu tho thao lao',
        'tủ thờ thao lao',
      ],
      negativeKeywords: [
        'tu quan ao',
        'tủ quần áo',
        'tu chen',
        'tủ chén',
        'tu bep',
        'tủ bếp'
      ],
      priority: 25,
    ),
    const SampleImageCategory(
      id: 'altar_standing_table',
      industry: 'Phòng thờ',
      name: 'Bàn thờ đứng trang nghiêm',
      imageUrl:
          'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ban tho',
        'bàn thờ',
        'ban tho dung',
        'bàn thờ đứng',
        'an gian tho',
        'án gian thờ',
        'sap tho',
        'sập thờ',
      ],
      negativeKeywords: ['ban an', 'bàn ăn', 'ban lam viec', 'bàn làm việc'],
      priority: 25,
    ),
    const SampleImageCategory(
      id: 'altar_wall_hanging',
      industry: 'Phòng thờ',
      name: 'Bàn thờ treo tường chung cư',
      imageUrl:
          'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ban tho treo tuong',
        'bàn thờ treo tường',
        'ban tho treo',
        'bàn thờ treo',
        'ban tho chung cu',
        'bàn thờ chung cư',
      ],
      priority: 23,
    ),
    const SampleImageCategory(
      id: 'altar_god_of_wealth',
      industry: 'Phòng thờ',
      name: 'Bàn thờ Thần Tài Thổ Địa',
      imageUrl:
          'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ban tho than tai',
        'bàn thờ thần tài',
        'ban tho ong dia',
        'bàn thờ ông địa',
        'ban tho than tai tho dia',
        'bàn thờ thần tài thổ địa',
        'tu than tai',
        'tủ thần tài',
      ],
      priority: 24,
    ),
    const SampleImageCategory(
      id: 'altar_incense_chair',
      industry: 'Phòng thờ',
      name: 'Ghế cao thắp nhang (Ghế đốt nhang gỗ có tay vịn)',
      imageUrl:
          'https://images.unsplash.com/photo-1503602642458-232111445657?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ghe dot nhang',
        'ghế đốt nhang',
        'ghe dot nhang go',
        'ghế đốt nhang gỗ',
        'ghe cao dot nhang',
        'ghế cao đốt nhang',
        'ghe thap nhang',
        'ghế thắp nhang',
        'ghe cao thap nhang',
        'ghế cao thắp nhang',
        'ghe thap huong',
        'ghế thắp hương',
      ],
      negativeKeywords: ['ghe xoay', 'ghế xoay', 'ghe an', 'ghế ăn'],
      priority: 25,
    ),
    const SampleImageCategory(
      id: 'altar_cnc_partition',
      industry: 'Phòng thờ',
      name: 'Vách ngăn phòng thờ CNC',
      imageUrl:
          'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'vach ngan phong tho',
        'vách ngăn phòng thờ',
        'vach cnc phong tho',
        'vách cnc phòng thờ',
        'vach ngan cnc',
        'vách ngăn cnc',
        'tam chong am khoi',
        'tấm chống ám khói',
      ],
      priority: 21,
    ),
    const SampleImageCategory(
      id: 'outdoor_swing_wrought_iron',
      industry: 'Sân vườn / Ngoài trời',
      name: 'Xích đu sắt mỹ thuật sơn tĩnh điện ngoài trời',
      imageUrl:
          'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'xich du sat',
        'xích đu sắt',
        'xich du',
        'xích đu',
        'xich du ngoai troi',
        'xích đu ngoài trời',
        'xich du my thuat',
        'xích đu mỹ thuật',
        'xich du son tinh dien',
        'xích đu sơn tĩnh điện',
        'sat 1122',
      ],
      negativeKeywords: ['ban chan sat', 'bàn chân sắt'],
      priority: 25,
    ),
    const SampleImageCategory(
      id: 'outdoor_swing_egg_rattan',
      industry: 'Sân vườn / Ngoài trời',
      name: 'Xích đu giọt nước mây nhựa',
      imageUrl:
          'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'xich du giot nuoc',
        'xích đu giọt nước',
        'xich du may nhua',
        'xích đu mây nhựa',
        'xich du qua trung',
        'xích đu quả trứng',
        'ghe xich du',
        'ghế xích đu',
      ],
      priority: 24,
    ),
    const SampleImageCategory(
      id: 'outdoor_swing_double',
      industry: 'Sân vườn / Ngoài trời',
      name: 'Xích đu đôi kèm nệm êm',
      imageUrl:
          'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'xich du doi',
        'xích đu đôi',
        'xich du 2 cho',
        'xích đu 2 chỗ',
        'xich du co dem',
        'xích đu có đệm',
      ],
      priority: 23,
    ),
    const SampleImageCategory(
      id: 'outdoor_cafe_table_chairs',
      industry: 'Sân vườn / Ngoài trời',
      name: 'Bộ bàn ghế cafe ngoài trời',
      imageUrl:
          'https://images.unsplash.com/photo-1519974719765-e6559eac2575?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ban ghe ngoai troi',
        'bàn ghế ngoài trời',
        'ban ghe cafe',
        'bàn ghế cafe',
        'ban ghe ban cong',
        'bàn ghế ban công',
        'ban ghe san vuon',
        'bàn ghế sân vườn',
      ],
      priority: 23,
    ),
    const SampleImageCategory(
      id: 'outdoor_relax_folding_chair',
      industry: 'Sân vườn / Ngoài trời',
      name: 'Ghế xếp thư giãn ban công',
      imageUrl:
          'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ghe xep thu gian',
        'ghế xếp thư giãn',
        'ghe thu gian ban cong',
        'ghế thư giãn ban công',
        'ghe bo ban cong',
        'ghế bố ban công',
        'ghe xep ngoai troi',
        'ghế xếp ngoài trời',
      ],
      priority: 22,
    ),
  ];

  /// Unexposed legacy list strictly for backward test compatibility for non-furniture categories
  static final List<SampleImageCategory> _legacyCatalog = [
    const SampleImageCategory(
      id: 'beverage_soda',
      industry: 'Đồ uống & Giải khát',
      name: 'Nước ngọt có ga & Nước tăng lực',
      imageUrl:
          'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'coca',
        'coca cola',
        'coca-cola',
        'pepsi',
        '7up',
        'sprite',
        'mirinda',
        'fanta',
        'sting',
        'redbull',
        'red bull',
        'monster',
        'bo huc',
        'bò húc',
        'nuoc ngot',
        'nước ngọt',
        'nuoc tang luc',
        'nước tăng lực',
        'nuoc co ga',
        'nước có ga',
        'soda',
        'lon nuoc',
        'lon nước',
        'number 1',
        'warrior',
        'wake up 247',
        'revive',
      ],
      negativeKeywords: ['ruou', 'rượu', 'bia'],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'beverage_beer',
      industry: 'Đồ uống & Giải khát',
      name: 'Bia & Thức uống có cồn',
      imageUrl:
          'https://images.unsplash.com/photo-1608270190807-6b45f1b1c313?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'heineken',
        'tiger',
        'bia saigon',
        'bia sai gon',
        'bia ha noi',
        'bia hà nội',
        'budweiser',
        'corona',
        'strongbow',
        'bia tươi',
        'bia lon',
        'bia chai',
        'ruou vang',
        'rượu vang',
        'whisky',
        'vodka',
        'bia',
        'rượu',
        'ruou',
        'chivas',
        'hoegaarden',
        'tuborg',
        'sapporo',
        'larue',
        '333',
        'bia 333',
        'soju',
      ],
      negativeKeywords: [
        'bìa',
        'bìa còng',
        'bìa hồ sơ',
        'bìa nhựa',
        'bìa carton',
        'bia cong',
        'bia ho so',
        'bia nhua',
        'bia carton',
        'bìa lá',
        'bia la',
        'bìa nút',
        'bia nut',
      ],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'beverage_milk',
      industry: 'Đồ uống & Giải khát',
      name: 'Sữa tươi & Sữa các loại',
      imageUrl:
          'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'vinamilk',
        'th true milk',
        'th milk',
        'milo',
        'dutch lady',
        'co gai ha lan',
        'cô gái hà lan',
        'sua tuoi',
        'sữa tươi',
        'sua dac',
        'sữa đặc',
        'sua bot',
        'sữa bột',
        'sua hat',
        'sữa hạt',
        'sua chua',
        'sữa chua',
        'sua dau nanh',
        'sữa đậu nành',
        'fami',
        'ong tho',
        'ông thọ',
        'nutifood',
        'ovalmaltine',
        'vitasoy',
        'vfresh sữa',
        'yakult',
        'probi',
        'sua bap',
        'sữa bắp',
      ],
      negativeKeywords: ['rua mat', 'rửa mặt', 'tam', 'tắm'],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'beverage_coffee',
      industry: 'Đồ uống & Giải khát',
      name: 'Cà phê & Bột cà phê',
      imageUrl:
          'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'trung nguyen',
        'trung nguyên',
        'highlands',
        'highland',
        'nescafe',
        'g7',
        'ca phe',
        'cà phê',
        'cafe',
        'capuchino',
        'cappuccino',
        'espresso',
        'latte',
        'ca phe sua',
        'cà phê sữa',
        'ca phe hoa tan',
        'cà phê hòa tan',
        'ca phe hat',
        'cà phê hạt',
        'phin ca phe',
        'phin cà phê',
        'starbucks',
        'king coffee',
        'wake up',
        'vina cafe',
      ],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'beverage_tea',
      industry: 'Đồ uống & Giải khát',
      name: 'Trà & Trà sữa',
      imageUrl:
          'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'tra xanh',
        'trà xanh',
        'tra dao',
        'trà đào',
        'tra chanh',
        'trà chanh',
        'tra sua',
        'trà sữa',
        'tra o long',
        'trà ô long',
        'lipton',
        'phuc long',
        'phúc long',
        'c2',
        'khong do',
        'không độ',
        'matcha',
        'hong tra',
        'hồng trà',
        'tui loc tra',
        'túi lọc trà',
        'tra atiso',
        'trà atisô',
        'tra thai',
        'trà thái',
        'cozy',
        'dilmah',
        'tra gung',
        'trà gừng',
      ],
      negativeKeywords: ['tra cuu', 'tra cứu', 'kiem tra', 'kiểm tra'],
      priority: 12,
    ),
    const SampleImageCategory(
      id: 'beverage_water',
      industry: 'Đồ uống & Giải khát',
      name: 'Nước suối & Nước tinh khiết',
      imageUrl:
          'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'aquafina',
        'lavie',
        'la vie',
        'dasani',
        'vinh hao',
        'vĩnh hảo',
        'th true water',
        'nuoc suoi',
        'nước suối',
        'nuoc khoang',
        'nước khoáng',
        'nuoc tinh khiet',
        'nước tinh khiết',
        'chai nuoc',
        'chai nước',
        'ion life',
        'vikoda',
      ],
      priority: 14,
    ),
    const SampleImageCategory(
      id: 'beverage_juice',
      industry: 'Đồ uống & Giải khát',
      name: 'Nước ép & Sinh tố',
      imageUrl:
          'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'nuoc cam',
        'nước cam',
        'nuoc ep',
        'nước ép',
        'sinh to',
        'sinh tố',
        'nuoc tao',
        'nước táo',
        'twister',
        'teppy',
        'vfresh',
        'nuoc dua',
        'nước dừa',
        'nuoc chanh day',
        'nước chanh dây',
        'nuoc ep trai cay',
        'nước ép trái cây',
        'smoothie',
        'juice',
      ],
      priority: 12,
    ),
    const SampleImageCategory(
      id: 'fmcg_laundry',
      industry: 'FMCG & Hóa phẩm giặt xả',
      name: 'Nước giặt, Bột giặt & Nước xả',
      imageUrl:
          'https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'omo',
        'tide',
        'ariel',
        'comfort',
        'downy',
        'surf',
        'lix',
        'aba',
        'nuoc giat',
        'nước giặt',
        'bot giat',
        'bột giặt',
        'nuoc xa vai',
        'nước xả vải',
        'xa vai',
        'xả vải',
        'hat giat',
        'hạt giặt',
        'nuoc tay javel',
        'nước tẩy javel',
        'dnee',
        'hygiene',
        'nuoc tay quan ao',
        'nước tẩy quần áo',
      ],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'fmcg_cleaning',
      industry: 'FMCG & Hóa phẩm',
      name: 'Nước rửa chén, Lau sàn & Tẩy rửa',
      imageUrl:
          'https://images.unsplash.com/photo-1585421514738-01798e348b17?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'sunlight',
        'my hao',
        'mỹ hảo',
        'vim',
        'duck',
        'gift',
        'nuoc rua chen',
        'nước rửa chén',
        'nuoc lau san',
        'nước lau sàn',
        'nuoc tay bon cau',
        'nước tẩy bồn cầu',
        'lau kinh',
        'lau kính',
        'sap thom phong',
        'sáp thơm phòng',
        'xịt phòng',
        'xit phong',
        'tay rua',
        'tẩy rửa',
        'thong cong',
        'thông cống',
      ],
      priority: 14,
    ),
    const SampleImageCategory(
      id: 'fmcg_tissue',
      industry: 'FMCG & Hóa phẩm',
      name: 'Khăn giấy & Giấy vệ sinh',
      imageUrl:
          'https://images.unsplash.com/photo-1584556812952-905ffd0c611a?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'pulppy',
        'paseo',
        'bless you',
        'emos',
        'giay ve sinh',
        'giấy vệ sinh',
        'khan giay',
        'khăn giấy',
        'khan giay an',
        'khăn giấy ăn',
        'khan uot',
        'khăn ướt',
        'giay an',
        'giấy ăn',
        'tissue',
        'giay cuon',
        'giấy cuộn',
        'khan lau mat',
        'khăn lau mặt',
      ],
      negativeKeywords: ['in a4', 'in ấn', 'giay in', 'giấy in'],
      priority: 14,
    ),
    const SampleImageCategory(
      id: 'fmcg_oral',
      industry: 'FMCG & Chăm sóc cá nhân',
      name: 'Kem đánh răng & Chăm sóc răng miệng',
      imageUrl:
          'https://images.unsplash.com/photo-1559591937-e10606134638?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'colgate',
        'p/s',
        'ps',
        'closeup',
        'close up',
        'sensodyne',
        'listerine',
        'kem danh rang',
        'kem đánh răng',
        'ban chai danh rang',
        'bàn chải đánh răng',
        'nuoc suc mieng',
        'nước súc miệng',
        'chi nha khoa',
        'chỉ nha khoa',
        'tam nuoc',
        'tăm nước',
        'bàn chải điện',
        'ban chai dien',
      ],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'fmcg_body_wash',
      industry: 'FMCG & Chăm sóc cá nhân',
      name: 'Dầu gội, Sữa tắm & Xà bông',
      imageUrl:
          'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'sunsilk',
        'clear',
        'head & shoulders',
        'head and shoulders',
        'pantene',
        'dove',
        'lifebuoy',
        'enchanteur',
        'romano',
        'x-men',
        'xmen',
        'dau goi',
        'dầu gội',
        'dau xa',
        'dầu xả',
        'sua tam',
        'sữa tắm',
        'xa bong',
        'xà bông',
        'xa phong',
        'xà phòng',
        'tresemme',
        'biore',
        'lux',
        'hazeline',
        'tam goi',
        'tắm gội',
      ],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'food_instant_noodles',
      industry: 'Thực phẩm & Đồ ăn vặt',
      name: 'Mì gói, Bún & Phở ăn liền',
      imageUrl:
          'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'hao hao',
        'hảo hảo',
        'omachi',
        'kokomi',
        'cung dinh',
        'cung đình',
        'mi tom',
        'mì tôm',
        'mi goi',
        'mì gói',
        'mi an lien',
        'mì ăn liền',
        'bun goi',
        'bún gói',
        'pho goi',
        'phở gói',
        'hu tieu an lien',
        'hủ tiếu ăn liền',
        'mien goi',
        'miến gói',
        'mi tron',
        'mì trộn',
        'koreno',
        'shin ramyun',
        'samyang',
        'indomie',
        'mi ly',
        'mì ly',
        'mi to',
        'mì tô',
      ],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'food_cookies_snacks',
      industry: 'Thực phẩm & Đồ ăn vặt',
      name: 'Bánh quy, Bánh ngọt & Snack',
      imageUrl:
          'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'danisa',
        'oreo',
        'chocopie',
        'custas',
        'cosy',
        'lay\'s',
        'lays',
        'oishi',
        'poca',
        'snack',
        'bim bim',
        'banh quy',
        'bánh quy',
        'banh ngot',
        'bánh ngọt',
        'banh bong lan',
        'bánh bông lan',
        'banh trang tron',
        'bánh tráng trộn',
        'banh gao',
        'bánh gạo',
        'banh mi',
        'bánh mì',
        'banh xop',
        'bánh xốp',
        'snack khoai tay',
        'snack khoai tây',
      ],
      negativeKeywords: ['banh xe', 'bánh xe', 'banh rang', 'bánh răng'],
      priority: 14,
    ),
    const SampleImageCategory(
      id: 'food_candies_chocolate',
      industry: 'Thực phẩm & Đồ ăn vặt',
      name: 'Kẹo & Sô-cô-la',
      imageUrl:
          'https://images.unsplash.com/photo-1581798459219-318e76aecc7b?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'chupa chups',
        'alpenliebe',
        'kitkat',
        'kit kat',
        'snickers',
        'm&m',
        'keo',
        'kẹo',
        'keo deo',
        'kẹo dẻo',
        'keo cao su',
        'kẹo cao su',
        'keo mut',
        'kẹo mút',
        'socola',
        'sô cô la',
        'chocolate',
        'keo ngam',
        'kẹo ngậm',
        'mentos',
        'dynamite',
      ],
      priority: 14,
    ),
    const SampleImageCategory(
      id: 'food_seasoning_oil',
      industry: 'Thực phẩm & Gia vị',
      name: 'Dầu ăn, Nước mắm & Gia vị',
      imageUrl:
          'https://images.unsplash.com/photo-1589135233689-d56d1a965780?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'simply',
        'neptune',
        'meizan',
        'knorr',
        'ajinomoto',
        'chinsu',
        'chin-su',
        'nam ngu',
        'nam ngư',
        'maggi',
        'nuoc mam',
        'nước mắm',
        'dau an',
        'dầu ăn',
        'nuoc tuong',
        'nước tương',
        'tuong ot',
        'tương ớt',
        'hat nem',
        'hạt nêm',
        'bot ngot',
        'bột ngọt',
        'muoi',
        'muối',
        'tieu',
        'tiêu',
        'duong cat',
        'đường cát',
        'duong phen',
        'đường phèn',
        'duong tinh luyen',
        'đường tinh luyện',
        'goi duong',
        'gói đường',
        'gia vi',
        'gia vị',
        'dau hao',
        'dầu hào',
        'sot mayonaise',
        'sốt',
        'cholimex',
        'ong cha va',
        'ông chà và',
      ],
      negativeKeywords: [
        'dau goi',
        'dầu gội',
        'dau gio',
        'dầu gió',
        'sua',
        'sữa',
        'pepsi',
        'coca',
        'nuoc ngot',
        'nước ngọt',
        'sting',
        'redbull',
        'tra',
        'trà',
        'bia',
        'cafe',
        'cà phê',
      ],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'food_rice_grains',
      industry: 'Thực phẩm',
      name: 'Gạo, Ngũ cốc & Hạt dinh dưỡng',
      imageUrl:
          'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'gao st25',
        'gạo st25',
        'gao thom',
        'gạo thơm',
        'gao lut',
        'gạo lứt',
        'yen mach',
        'yến mạch',
        'granola',
        'hat dieu',
        'hạt điều',
        'hanh nhan',
        'hạnh nhân',
        'hat de',
        'hạt dẻ',
        'hat sen',
        'hạt sen',
        'ngu coc',
        'ngũ cốc',
        'gao nang hoa',
        'gạo nàng hoa',
        'gao nep',
        'gạo nếp',
        'hat chia',
        'hạt chia',
        'hat macca',
        'hạt macca',
      ],
      priority: 14,
    ),
    const SampleImageCategory(
      id: 'food_canned_sausage',
      industry: 'Thực phẩm',
      name: 'Xúc xích & Đồ hộp',
      imageUrl:
          'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'vissan',
        'cp',
        'c.p',
        'xuc xich',
        'xúc xích',
        'thit hop',
        'thịt hộp',
        'ca hop',
        'cá hộp',
        'pate',
        'lap xuong',
        'lạp xưởng',
        'cha lua',
        'chả lụa',
        'do hop',
        'đồ hộp',
        'spam',
        '3 co gai',
        '3 cô gái',
        'heo cao boi',
        'heo cao bồi',
        'ponnie',
      ],
      priority: 14,
    ),
    const SampleImageCategory(
      id: 'fresh_fruits',
      industry: 'Nông sản tươi sống',
      name: 'Trái cây & Rau củ quả',
      imageUrl:
          'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'trai cay',
        'trái cây',
        'hoa qua',
        'hoa quả',
        'cam',
        'tao',
        'táo',
        'chuoi',
        'chuối',
        'nho',
        'xoai',
        'xoài',
        'dua hau',
        'dưa hấu',
        'buoi',
        'bưởi',
        'sau rieng',
        'sầu riêng',
        'thanh long',
        'rau xanh',
        'bap cai',
        'bắp cải',
        'ca chua',
        'cà chua',
        'khoai tay',
        'khoai tây',
        'nam',
        'nấm',
        'cu qua',
        'củ quả',
        'rau cu',
        'rau củ',
      ],
      negativeKeywords: ['nuoc cam', 'nước cam', 'nuoc ep', 'nước ép'],
      priority: 12,
    ),
    const SampleImageCategory(
      id: 'fresh_meat_seafood',
      industry: 'Nông sản tươi sống',
      name: 'Thịt tươi sống & Hải sản',
      imageUrl:
          'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'thit heo',
        'thịt heo',
        'thit bo',
        'thịt bò',
        'thit ga',
        'thịt gà',
        'thit vit',
        'thịt vịt',
        'ca hoi',
        'cá hồi',
        'tom',
        'tôm',
        'cua',
        'muc',
        'mực',
        'ngheu',
        'nghêu',
        'so',
        'sò',
        'oc',
        'ốc',
        'thuy hai san',
        'thủy hải sản',
        'thit tuoi',
        'thịt tươi',
        'hai san',
        'hải sản',
      ],
      negativeKeywords: [
        'sổ',
        'so tay',
        'sổ tay',
        'sổ còng',
        'so cong',
        'mực in',
        'muc in',
        'mực bút',
        'muc but',
        'mực máy in',
        'muc may in',
        'mực viết',
        'muc viet',
      ],
      priority: 13,
    ),
    const SampleImageCategory(
      id: 'cosmetics_lipstick',
      industry: 'Mỹ phẩm & Chăm sóc sắc đẹp',
      name: 'Son môi & Trang điểm môi',
      imageUrl:
          'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&auto=format&fit=crop&q=80',
      keywords: [
        '3ce',
        'mac',
        'black rouge',
        'dior lip',
        'maybelline lip',
        'romand',
        'son moi',
        'son môi',
        'son kem',
        'son thoi',
        'son thỏi',
        'son bong',
        'son bóng',
        'son duong',
        'son dưỡng',
        'son tint',
        'son li',
        'son lì',
        'lipstick',
      ],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'cosmetics_makeup',
      industry: 'Mỹ phẩm & Làm đẹp',
      name: 'Trang điểm mặt & Mắt',
      imageUrl:
          'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'kem nen',
        'kem nền',
        'phan phu',
        'phấn phủ',
        'cushion',
        'che khuyet diem',
        'che khuyết điểm',
        'mascara',
        'eyeliner',
        'phan mat',
        'phấn mắt',
        'chi ke may',
        'chì kẻ mày',
        'bong trang diem',
        'bông trang điểm',
        'kem lot',
        'kem lót',
        'bb cream',
        'cc cream',
        'phan ma hong',
        'phấn má hồng',
      ],
      priority: 14,
    ),
    const SampleImageCategory(
      id: 'cosmetics_skincare',
      industry: 'Mỹ phẩm & Làm đẹp',
      name: 'Skincare & Dưỡng da',
      imageUrl:
          'https://images.unsplash.com/photo-1608248597359-577765103c80?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'anessa',
        'la roche posay',
        'la roche-posay',
        'innisfree',
        'cerave',
        'vichy',
        'l\'oreal',
        'loreal',
        'serum',
        'kem chong nang',
        'kem chống nắng',
        'toner',
        'sua rua mat',
        'sữa rửa mặt',
        'nuoc tay trang',
        'nước tẩy trang',
        'kem duong da',
        'kem dưỡng da',
        'mat na',
        'mặt nạ',
        'te bao chet',
        'tế bào chết',
        'nuoc hoa hong',
        'nước hoa hồng',
        'tinh chat',
        'tinh chất',
        'klairs',
        'the ordinary',
        'cosrx',
        'hada labo',
        'simple',
      ],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'cosmetics_perfume',
      industry: 'Mỹ phẩm & Làm đẹp',
      name: 'Nước hoa & Tinh dầu',
      imageUrl:
          'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'chanel',
        'gucci',
        'versace',
        'dior sauvage',
        'narciso',
        'nuoc hoa',
        'nước hoa',
        'perfume',
        'tinh dau thom',
        'tinh dầu thơm',
        'body mist',
        'xit khu mui',
        'xịt khử mùi',
        'dau thom',
        'dầu thơm',
        'edp',
        'edt',
        'nuoc hoa nam',
        'nước hoa nam',
        'nuoc hoa nu',
        'nước hoa nữ',
      ],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'cosmetics_personal_care',
      industry: 'Chăm sóc cá nhân',
      name: 'Dao cạo & Vệ sinh cá nhân',
      imageUrl:
          'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'gillette',
        'kotex',
        'diana',
        'dao cao rau',
        'dao cạo râu',
        'bot cao rau',
        'bọt cạo râu',
        'bang ve sinh',
        'băng vệ sinh',
        'mieng dan',
        'miếng dán',
        'dung dich ve sinh',
        'dung dịch vệ sinh',
        'tam bong',
        'tăm bông',
      ],
      priority: 14,
    ),
    const SampleImageCategory(
      id: 'fashion_tops',
      industry: 'Thời trang & May mặc',
      name: 'Áo thun, Sơ mi & Áo polo',
      imageUrl:
          'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ao thun',
        'áo thun',
        'ao phong',
        'áo phông',
        't-shirt',
        'ao so mi',
        'áo sơ mi',
        'ao polo',
        'áo polo',
        'ao kieu',
        'áo kiểu',
        'ao croptop',
        'áo croptop',
        'ao ba lo',
        'áo ba lỗ',
        'ao coc',
        'áo cộc',
        'ao thun nam',
        'áo thun nam',
        'ao thun nu',
        'áo thun nữ',
      ],
      negativeKeywords: [
        'bao cao',
        'báo cáo',
        'quang cao',
        'quảng cáo',
        'phao',
        'pháo',
        'thong bao',
        'thông báo',
      ],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'fashion_pants',
      industry: 'Thời trang & May mặc',
      name: 'Quần jean, Kaki & Quần tây',
      imageUrl:
          'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'levi\'s',
        'levis',
        'quan jean',
        'quần jean',
        'quan bo',
        'quần bò',
        'quan kaki',
        'quần kaki',
        'quan tay',
        'quần tây',
        'quan short',
        'quần short',
        'quan lung',
        'quần lửng',
        'quan ong rong',
        'quần ống rộng',
        'quan dui',
        'quần đùi',
        'quan dai',
        'quần dài',
        'quan jogger',
        'quần jogger',
      ],
      negativeKeywords: ['khăn', 'khan'],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'fashion_outerwear',
      industry: 'Thời trang & May mặc',
      name: 'Áo khoác, Hoodie & Sweater',
      imageUrl:
          'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ao khoac',
        'áo khoác',
        'ao gio',
        'áo gió',
        'ao hoodie',
        'áo hoodie',
        'ao sweater',
        'áo sweater',
        'ao blazer',
        'áo blazer',
        'ao da',
        'áo dạ',
        'ao mang to',
        'áo măng tô',
        'ao vest',
        'áo vest',
        'ao len',
        'áo len',
        'jacket',
        'cardigan',
      ],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'fashion_dresses',
      industry: 'Thời trang & May mặc',
      name: 'Váy & Đầm nữ',
      imageUrl:
          'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'dam',
        'đầm',
        'vay',
        'váy',
        'chan vay',
        'chân váy',
        'dam xoe',
        'đầm xòe',
        'dam da hoi',
        'đầm dạ hội',
        'ao dai',
        'áo dài',
        'set do nu',
        'set đồ nữ',
        'jumpsuit',
        'dam cong so',
        'đầm công sở',
        'vay maxi',
        'váy maxi',
      ],
      priority: 14,
    ),
    const SampleImageCategory(
      id: 'fashion_underwear',
      industry: 'Thời trang & May mặc',
      name: 'Đồ lót & Đồ ngủ',
      imageUrl:
          'https://images.unsplash.com/photo-1574634534894-89d7576c8259?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'do lot',
        'đồ lót',
        'do ngu',
        'đồ ngủ',
        'pijama',
        'ao nguc',
        'áo ngực',
        'quan lot',
        'quần lót',
        'boxer',
        'tat chan',
        'tất chân',
        'vo chan',
        'vớ chân',
        'quan sip',
        'quần sịp',
        'bra',
      ],
      priority: 13,
    ),
    const SampleImageCategory(
      id: 'shoes_sneakers',
      industry: 'Giày dép & Túi xách',
      name: 'Giày sneaker & Thể thao',
      imageUrl:
          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'nike',
        'adidas',
        'puma',
        'converse',
        'vans',
        'biti\'s',
        'bitis',
        'hunter',
        'giay the thao',
        'giày thể thao',
        'sneaker',
        'giay chay bo',
        'giày chạy bộ',
        'giay tap gym',
        'giày tập gym',
        'giay nam',
        'giày nam',
        'giay nu',
        'giày nữ',
        'jordan',
        'air force',
        'stan smith',
      ],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'shoes_formal',
      industry: 'Giày dép & Túi xách',
      name: 'Giày da, Giày tây & Cao gót',
      imageUrl:
          'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'giay da',
        'giày da',
        'giay tay',
        'giày tây',
        'giay oxford',
        'giày oxford',
        'giay luoi',
        'giày lười',
        'loafer',
        'giay cao got',
        'giày cao gót',
        'boot',
        'boots',
        'giay bup be',
        'giày búp bê',
      ],
      priority: 14,
    ),
    const SampleImageCategory(
      id: 'shoes_sandals',
      industry: 'Giày dép & Túi xách',
      name: 'Dép & Sandal',
      imageUrl:
          'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'dep',
        'dép',
        'sandal',
        'xang dan',
        'xăng đan',
        'dep quai ngang',
        'dép quai ngang',
        'dep xo ngon',
        'dép xỏ ngón',
        'dep banh mi',
        'dép bánh mì',
        'dep tong',
        'dép tông',
        'crocs',
        'dep di trong nha',
        'dép đi trong nhà',
      ],
      priority: 14,
    ),
    const SampleImageCategory(
      id: 'bags_handbags',
      industry: 'Giày dép & Túi xách',
      name: 'Túi xách, Bóp ví & Thắt lưng',
      imageUrl:
          'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'tui xach',
        'túi xách',
        'tui deo cheo',
        'túi đeo chéo',
        'vi da',
        'ví da',
        'bop tien',
        'bóp tiền',
        'that lung',
        'thắt lưng',
        'day nit',
        'dây nịt',
        'clutch',
        'tui tote',
        'túi tote',
        'vi nu',
        'ví nữ',
        'vi nam',
        'ví nam',
      ],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'bags_backpacks',
      industry: 'Giày dép & Hành lý',
      name: 'Balo & Vali du lịch',
      imageUrl:
          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'balo',
        'ba lo',
        'vali',
        'tui du lich',
        'túi du lịch',
        'balo laptop',
        'balo học sinh',
        'balo hoc sinh',
        'tui chong soc',
        'túi chống sốc',
        'backpack',
        'luggage',
      ],
      priority: 14,
    ),
    const SampleImageCategory(
      id: 'fashion_accessories',
      industry: 'Phụ kiện thời trang',
      name: 'Mũ nón & Kính mát',
      imageUrl:
          'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'mu',
        'mũ',
        'non',
        'nón',
        'mu luoi trai',
        'mũ lưỡi trai',
        'non ket',
        'nón kết',
        'non bucket',
        'nón bucket',
        'kinh mat',
        'kính mát',
        'kinh ram',
        'kính râm',
        'kinh thoi trang',
        'kính thời trang',
        'kinh can',
        'kính cận',
        'khan choang',
        'khăn choàng',
        'gang tay',
        'găng tay',
      ],
      negativeKeywords: ['kính cường lực', 'kinh cuong luc'],
      priority: 12,
    ),
    const SampleImageCategory(
      id: 'tech_iphone',
      industry: 'Điện máy & Công nghệ',
      name: 'Apple iPhone',
      imageUrl:
          'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'iphone',
        'iphone 15',
        'iphone 16',
        'iphone 14',
        'iphone 13',
        'iphone 12',
        'iphone 11',
        'iphone pro max',
        'apple phone',
        'dien thoai iphone',
        'điện thoại iphone',
      ],
      negativeKeywords: [
        'ốp lưng',
        'op lung',
        'bao da',
        'kính cường lực',
        'kinh cuong luc'
      ],
      priority: 25,
    ),
    const SampleImageCategory(
      id: 'tech_android',
      industry: 'Điện máy & Công nghệ',
      name: 'Android Smartphone',
      imageUrl:
          'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'samsung',
        'galaxy',
        'xiaomi',
        'oppo',
        'vivo',
        'realme',
        'dien thoai',
        'điện thoại',
        'smartphone',
        'redmi',
        'poco',
        'oneplus',
        'sony xperia',
      ],
      negativeKeywords: [
        'ốp lưng',
        'op lung',
        'bao da',
        'kính cường lực',
        'kinh cuong luc',
        'dien thoai ban'
      ],
      priority: 20,
    ),
    const SampleImageCategory(
      id: 'tech_laptop',
      industry: 'Điện máy & Công nghệ',
      name: 'Laptop & MacBook',
      imageUrl:
          'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'macbook',
        'laptop',
        'dell',
        'asus',
        'lenovo',
        'thinkpad',
        'acer',
        'hp',
        'may tinh xach tay',
        'máy tính xách tay',
        'notebook',
        'macbook pro',
        'macbook air',
        'gaming laptop',
      ],
      negativeKeywords: [
        'balo laptop',
        'ba lo',
        'túi chống sốc',
        'tui chong soc'
      ],
      priority: 22,
    ),
    const SampleImageCategory(
      id: 'tech_tablet',
      industry: 'Điện máy & Công nghệ',
      name: 'Tablet & iPad',
      imageUrl:
          'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'ipad',
        'tablet',
        'ipad pro',
        'ipad air',
        'may tinh bang',
        'máy tính bảng',
        'galaxy tab',
        'tab s9',
      ],
      negativeKeywords: ['bao da', 'bao da ipad', 'ốp', 'op'],
      priority: 20,
    ),
    const SampleImageCategory(
      id: 'tech_desktop_monitor',
      industry: 'Điện máy & Công nghệ',
      name: 'Màn hình & Máy tính để bàn',
      imageUrl:
          'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'man hinh',
        'màn hình',
        'monitor',
        'desktop',
        'pc',
        'case may tinh',
        'case máy tính',
        'may tinh de ban',
        'máy tính để bàn',
        'all in one',
        'cpu',
        'vga',
        'card man hinh',
        'card màn hình',
      ],
      priority: 18,
    ),
    const SampleImageCategory(
      id: 'tech_earbuds',
      industry: 'Thiết bị âm thanh',
      name: 'Tai nghe & AirPods',
      imageUrl:
          'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'airpod',
        'airpods',
        'tws',
        'tai nghe khong day',
        'tai nghe không dây',
        'tai nghe bluetooth',
        'earbuds',
        'tai nghe sony',
        'galaxy buds',
      ],
      priority: 18,
    ),
    const SampleImageCategory(
      id: 'tech_headphones_speakers',
      industry: 'Thiết bị âm thanh',
      name: 'Tai nghe chụp tai & Loa Bluetooth',
      imageUrl:
          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'headphone',
        'headset',
        'tai nghe chup tai',
        'tai nghe chụp tai',
        'loa',
        'loa bluetooth',
        'loa jbl',
        'marshall',
        'soundbar',
        'loa keo',
        'loa kéo',
        'micro',
        'dan am thanh',
        'dàn âm thanh',
      ],
      priority: 16,
    ),
    const SampleImageCategory(
      id: 'tech_smartwatch',
      industry: 'Phụ kiện công nghệ',
      name: 'Đồng hồ thông minh & Smartwatch',
      imageUrl:
          'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'apple watch',
        'smartwatch',
        'garmin',
        'galaxy watch',
        'dong ho thong minh',
        'đồng hồ thông minh',
        'dong ho',
        'đồng hồ',
        'vong deo tay thong minh',
        'vòng đeo tay thông minh',
      ],
      priority: 16,
    ),
    const SampleImageCategory(
      id: 'tech_keyboard_mouse',
      industry: 'Phụ kiện công nghệ',
      name: 'Bàn phím & Chuột máy tính',
      imageUrl:
          'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'logitech',
        'ban phim',
        'bàn phím',
        'keyboard',
        'phim co',
        'phím cơ',
        'chuot may tinh',
        'chuột máy tính',
        'mouse',
        'chuot khong day',
        'chuột không dây',
        'lot chuot',
        'lót chuột',
      ],
      priority: 16,
    ),
    const SampleImageCategory(
      id: 'tech_chargers_cables',
      industry: 'Phụ kiện công nghệ',
      name: 'Sạc cáp & Pin dự phòng',
      imageUrl:
          'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'anker',
        'ugreen',
        'cu sac',
        'củ sạc',
        'cap sac',
        'cáp sạc',
        'day sac',
        'dây sạc',
        'sac nhanh',
        'sạc nhanh',
        'type-c',
        'lightning',
        'sac du phong',
        'sạc dự phòng',
        'powerbank',
        'pin sac',
        'pin sạc',
        'dock sac',
        'dock sạc',
        'tau sac',
        'tẩu sạc',
      ],
      negativeKeywords: ['cao cấp', 'cao cap'],
      priority: 18,
    ),
    const SampleImageCategory(
      id: 'tech_cases_protectors',
      industry: 'Phụ kiện công nghệ',
      name: 'Ốp lưng & Kính cường lực',
      imageUrl:
          'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'op lung',
        'ốp lưng',
        'bao da',
        'kinh cuong luc',
        'kính cường lực',
        'dan man hinh',
        'dán màn hình',
        'case dien thoai',
        'case điện thoại',
        'op dien thoai',
        'ốp điện thoại',
        'bao da ipad',
        'mieng dan ppf',
        'miếng dán ppf',
      ],
      priority: 22,
    ),
    const SampleImageCategory(
      id: 'tech_camera',
      industry: 'Thiết bị số',
      name: 'Máy ảnh, Camera & Flycam',
      imageUrl:
          'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'may anh',
        'máy ảnh',
        'camera',
        'sony alpha',
        'canon',
        'nikon',
        'fujifilm',
        'webcam',
        'flycam',
        'dji',
        'camera hanh trinh',
        'camera hành trình',
        'gopro',
        'lens may anh',
        'ống kính máy ảnh',
      ],
      priority: 16,
    ),
    const SampleImageCategory(
      id: 'home_kitchen_appliances',
      industry: 'Đồ gia dụng & Nhà cửa',
      name: 'Thiết bị nhà bếp & Điện gia dụng',
      imageUrl:
          'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'philips',
        'tefal',
        'sunhouse',
        'lock&lock',
        'lock and lock',
        'noi chien khong dau',
        'nồi chiên không dầu',
        'noi com dien',
        'nồi cơm điện',
        'am sieu toc',
        'ấm siêu tốc',
        'may xay sinh to',
        'máy xay sinh tố',
        'lo vi song',
        'lò vi sóng',
        'bep tu',
        'bếp từ',
        'may ep cham',
        'máy ép chậm',
        'bep ga',
        'bếp ga',
        'noi ap suat',
        'nồi áp suất',
      ],
      priority: 16,
    ),
    const SampleImageCategory(
      id: 'home_cleaning_appliances',
      industry: 'Đồ gia dụng & Nhà cửa',
      name: 'Quạt điện, Máy lọc khí & Hút bụi',
      imageUrl:
          'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'quat dien',
        'quạt điện',
        'quat cay',
        'quạt cây',
        'quat tich dien',
        'quạt tích điện',
        'may loc khong khi',
        'máy lọc không khí',
        'may hut bui',
        'máy hút bụi',
        'robot hut bui',
        'robot hút bụi',
        'ban ui',
        'bàn ủi',
        'ban la',
        'bàn là',
        'may say quan ao',
        'máy sấy quần áo',
      ],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'home_cookware_dining',
      industry: 'Đồ gia dụng & Nhà cửa',
      name: 'Bộ nồi chảo, Bát đĩa & Cốc chén',
      imageUrl:
          'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'chao chong dinh',
        'chảo chống dính',
        'bo noi',
        'bộ nồi',
        'bat dia',
        'bát đĩa',
        'chen dia',
        'chén dĩa',
        'to su',
        'tô sứ',
        'ly thuy tinh',
        'ly thủy tinh',
        'binh giu nhiet',
        'bình giữ nhiệt',
        'hop thuc pham',
        'hộp thực phẩm',
        'dao thot',
        'dao thớt',
        'dua muong',
        'đũa muỗng',
      ],
      priority: 14,
    ),
    const SampleImageCategory(
      id: 'pharma_otc_medicines',
      industry: 'Dược phẩm & Y tế',
      name: 'Thuốc OTC & Cồn y tế',
      imageUrl:
          'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'panadol',
        'efferalgan',
        'thuoc cam',
        'thuốc cảm',
        'thuoc ho',
        'thuốc ho',
        'nuoc nho mat',
        'nước nhỏ mắt',
        'con y te',
        'cồn y tế',
        'con 70 do',
        'cồn 70 độ',
        'dau gio',
        'dầu gió',
        'dau tram',
        'dầu tràm',
        'bong bang gac',
        'bông băng gạc',
        'thuoc',
        'thuốc',
        'berberin',
        'salonpas',
      ],
      negativeKeywords: [
        'thước',
        'thuoc ke',
        'thước kẻ',
        'thước đo',
        'thuoc do',
        'thước nhôm',
        'thuoc nhom',
        'thước dây',
        'thuoc day',
      ],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'pharma_face_masks',
      industry: 'Dược phẩm & Y tế',
      name: 'Khẩu trang y tế & Sát khuẩn',
      imageUrl:
          'https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'khau trang',
        'khẩu trang',
        'khau trang y te',
        'khẩu trang y tế',
        'khau trang 4d',
        'khẩu trang 4d',
        'kf94',
        'nuoc rua tay',
        'nước rửa tay',
        'dung dich sat khuan',
        'dung dịch sát khuẩn',
        'gel rua tay',
        'gel rửa tay',
        'sat khuan',
        'sát khuẩn',
      ],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'pharma_supplements',
      industry: 'Dược phẩm & Y tế',
      name: 'Thực phẩm chức năng & Vitamin',
      imageUrl:
          'https://images.unsplash.com/photo-1577401239170-897942555fb3?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'vitamin c',
        'omega 3',
        'dau ca',
        'dầu cá',
        'canxi',
        'collagen',
        'glucosamine',
        'thuc pham chuc nang',
        'thực phẩm chức năng',
        'vien uong bo sung',
        'viên uống bổ sung',
        'vitamin',
        'kem bo sung',
        'dha',
        'men vi sinh',
      ],
      priority: 14,
    ),
    const SampleImageCategory(
      id: 'pharma_medical_devices',
      industry: 'Dược phẩm & Y tế',
      name: 'Thiết bị y tế gia đình',
      imageUrl:
          'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'omron',
        'microlife',
        'may do huyet ap',
        'máy đo huyết áp',
        'nhiet ke dien tu',
        'nhiệt kế điện tử',
        'may do duong huyet',
        'máy đo đường huyết',
        'may xong mui hong',
        'máy xông mũi họng',
        'can suc khoe',
        'cân sức khỏe',
      ],
      priority: 16,
    ),
    const SampleImageCategory(
      id: 'stationery_pens',
      industry: 'Văn phòng phẩm',
      name: 'Bút viết & Dụng cụ vẽ',
      imageUrl:
          'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'thien long',
        'thiên long',
        'but bi',
        'bút bi',
        'but gel',
        'bút gel',
        'but da quang',
        'bút dạ quang',
        'but chi',
        'bút chì',
        'but xoa',
        'bút xóa',
        'but long',
        'bút lông',
        'mau ve',
        'màu vẽ',
        'thuoc ke',
        'thước kẻ',
        'gom tay',
        'gôm tẩy',
        'but highlight',
        'muc in',
        'mực in',
        'muc but',
        'mực bút',
      ],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'stationery_notebooks_paper',
      industry: 'Văn phòng phẩm',
      name: 'Sổ tay, Vở & Giấy in',
      imageUrl:
          'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'double a',
        'campus',
        'so tay',
        'sổ tay',
        'vo hoc sinh',
        'vở học sinh',
        'giay in',
        'giấy in',
        'giay a4',
        'giấy a4',
        'giay note',
        'giấy note',
        'tap vo',
        'tập vở',
        'so lo xo',
        'sổ lò xo',
        'so cong',
        'sổ còng',
        'so',
        'sổ',
      ],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'stationery_tools_calculators',
      industry: 'Văn phòng phẩm',
      name: 'Dụng cụ văn phòng & Máy tính bỏ túi',
      imageUrl:
          'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'casio',
        'may tinh casio',
        'máy tính casio',
        'may tinh cam tay',
        'máy tính cầm tay',
        'bang keo',
        'băng keo',
        'bang dinh',
        'băng dính',
        'keo dan',
        'kéo',
        'bam kim',
        'bấm kim',
        'bia cong',
        'bìa còng',
        'bia nhua',
        'bìa nhựa',
        'bia ho so',
        'bìa hồ sơ',
        'bia',
        'bìa',
        'kep giay',
        'kẹp giấy',
        'thuoc',
        'thước',
      ],
      priority: 14,
    ),
    const SampleImageCategory(
      id: 'baby_diapers',
      industry: 'Mẹ & Bé',
      name: 'Tã bỉm cho bé',
      imageUrl:
          'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'bobby',
        'huggies',
        'moony',
        'merries',
        'pampers',
        'ta dan',
        'tã dán',
        'ta quan',
        'tã quần',
        'bim cho be',
        'bỉm cho bé',
        'ta bim',
        'tã bỉm',
        'bim quan',
        'bỉm quần',
      ],
      priority: 16,
    ),
    const SampleImageCategory(
      id: 'baby_feeding_toys',
      industry: 'Mẹ & Bé',
      name: 'Bình sữa & Đồ dùng trẻ em',
      imageUrl:
          'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'hegen',
        'pigeon',
        'binh sua',
        'bình sữa',
        'num ti',
        'núm ti',
        'may ham sua',
        'máy hâm sữa',
        'xe day em be',
        'xe đẩy em bé',
        'do choi tre em',
        'đồ chơi trẻ em',
        'ti gia',
        'ti giả',
        'ghe an dam',
        'ghế ăn dặm',
      ],
      priority: 15,
    ),
    const SampleImageCategory(
      id: 'pet_food',
      industry: 'Thú cưng',
      name: 'Thức ăn & Phụ kiện thú cưng',
      imageUrl:
          'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'royal canin',
        'me-o',
        'meo',
        'whiskas',
        'thuc an meo',
        'thức ăn mèo',
        'thuc an cho',
        'thức ăn chó',
        'hat cho meo',
        'hạt cho mèo',
        'pate cho cho meo',
        'pate cho chó mèo',
        'cat ve sinh meo',
        'cát vệ sinh mèo',
        'phu kien thu cung',
        'phụ kiện thú cưng',
        'vong co cho meo',
        'vòng cổ chó mèo',
      ],
      priority: 16,
    ),
    const SampleImageCategory(
      id: 'gift_combo',
      industry: 'Combo / Quà tặng',
      name: 'Combo & Giỏ quà tặng',
      imageUrl:
          'https://images.unsplash.com/photo-1512756290469-ec264b7fbf87?w=600&auto=format&fit=crop&q=80',
      keywords: [
        'combo',
        'gio qua',
        'giỏ quà',
        'hop qua',
        'hộp quà',
        'set qua',
        'set quà',
        'qua tet',
        'quà tết',
        'combo qua tang',
        'combo quà tặng',
        'goi qua',
        'gói quà',
        'gift set',
        'gift box',
      ],
      priority: 20,
    ),
  ];

  /// Find all categories (includes legacy for test backwards compatibility)
  static List<SampleImageCategory> getAllCategories() =>
      [...catalog, ..._legacyCatalog];

  /// Calculate relevance score for a category given search inputs
  static int _calculateScore({
    required SampleImageCategory cat,
    required String name,
    required String category,
    required String brand,
    required String category3Levels,
    required bool isCombo,
  }) {
    if (isCombo && cat.id == 'gift_combo') {
      return 100 + cat.priority;
    }

    final nameAcc = VietnameseTextHelper.normalize(name);
    final nameUnacc = VietnameseTextHelper.normalizeUnaccented(name);
    final catAcc = VietnameseTextHelper.normalize(category);
    final catUnacc = VietnameseTextHelper.normalizeUnaccented(category);
    final brandAcc = VietnameseTextHelper.normalize(brand);
    final brandUnacc = VietnameseTextHelper.normalizeUnaccented(brand);
    final treeAcc = VietnameseTextHelper.normalize(category3Levels);
    final treeUnacc = VietnameseTextHelper.normalizeUnaccented(category3Levels);

    // 1. Negative keywords exclusion
    for (final neg in cat.negativeKeywords) {
      final negAcc = VietnameseTextHelper.normalize(neg);
      if (negAcc.isEmpty) continue;
      final isMulti = negAcc.contains(' ');
      if (isMulti) {
        final negUnacc = VietnameseTextHelper.normalizeUnaccented(neg);
        if (VietnameseTextHelper.containsPhrase(nameAcc, negAcc) ||
            VietnameseTextHelper.containsPhrase(nameUnacc, negUnacc,
                unaccented: true) ||
            VietnameseTextHelper.containsPhrase(catAcc, negAcc) ||
            VietnameseTextHelper.containsPhrase(catUnacc, negUnacc,
                unaccented: true)) {
          return -100;
        }
      } else {
        final hasAccents =
            VietnameseTextHelper.removeDiacritics(negAcc) != negAcc;
        if (hasAccents) {
          if (VietnameseTextHelper.containsWord(nameAcc, negAcc) ||
              VietnameseTextHelper.containsWord(catAcc, negAcc)) {
            return -100;
          }
        } else {
          final negUnacc = VietnameseTextHelper.normalizeUnaccented(neg);
          if (VietnameseTextHelper.containsWord(nameAcc, negAcc) ||
              VietnameseTextHelper.containsWordUnaccented(
                  nameUnacc, negUnacc) ||
              VietnameseTextHelper.containsWord(catAcc, negAcc) ||
              VietnameseTextHelper.containsWordUnaccented(catUnacc, negUnacc)) {
            return -100;
          }
        }
      }
    }

    int score = cat.priority;
    int matchesCount = 0;
    final matchedConcepts = <String>{};

    for (final kw in cat.keywords) {
      final kwAcc = VietnameseTextHelper.normalize(kw);
      final kwUnacc = VietnameseTextHelper.normalizeUnaccented(kw);
      if (kwAcc.isEmpty) continue;

      // Prevent duplicate score stacking for the same keyword concept
      if (matchedConcepts.contains(kwUnacc)) continue;

      final isMultiWord = kwAcc.contains(' ');

      if (isMultiWord) {
        // Multi-word phrase matching
        if (VietnameseTextHelper.containsPhrase(nameAcc, kwAcc) ||
            VietnameseTextHelper.containsPhrase(nameUnacc, kwUnacc,
                unaccented: true)) {
          score += 30;
          matchesCount++;
          matchedConcepts.add(kwUnacc);
        } else if (VietnameseTextHelper.containsPhrase(catAcc, kwAcc) ||
            VietnameseTextHelper.containsPhrase(catUnacc, kwUnacc,
                unaccented: true) ||
            VietnameseTextHelper.containsPhrase(treeAcc, kwAcc) ||
            VietnameseTextHelper.containsPhrase(treeUnacc, kwUnacc,
                unaccented: true)) {
          score += 20;
          matchesCount++;
          matchedConcepts.add(kwUnacc);
        } else if (brandAcc.isNotEmpty &&
            (VietnameseTextHelper.containsPhrase(brandAcc, kwAcc) ||
                VietnameseTextHelper.containsPhrase(brandUnacc, kwUnacc,
                    unaccented: true))) {
          score += 20;
          matchesCount++;
          matchedConcepts.add(kwUnacc);
        }
      } else {
        // Single word boundary matching
        if (VietnameseTextHelper.containsWord(nameAcc, kwAcc) ||
            VietnameseTextHelper.containsWordUnaccented(nameUnacc, kwUnacc)) {
          score += 15;
          matchesCount++;
          matchedConcepts.add(kwUnacc);
        } else if (VietnameseTextHelper.containsWord(catAcc, kwAcc) ||
            VietnameseTextHelper.containsWordUnaccented(catUnacc, kwUnacc) ||
            VietnameseTextHelper.containsWord(treeAcc, kwAcc) ||
            VietnameseTextHelper.containsWordUnaccented(treeUnacc, kwUnacc)) {
          score += 10;
          matchesCount++;
          matchedConcepts.add(kwUnacc);
        } else if (brandAcc.isNotEmpty &&
            (VietnameseTextHelper.containsWord(brandAcc, kwAcc) ||
                VietnameseTextHelper.containsWordUnaccented(
                    brandUnacc, kwUnacc))) {
          score += 15;
          matchesCount++;
          matchedConcepts.add(kwUnacc);
        }
      }
    }

    if (matchesCount == 0) {
      return 0;
    }

    return score;
  }

  /// Get list of top suggested images ranked by relevance score
  static List<SampleImageMatch> getSuggestedImages(
    Product product, {
    bool furnitureOnly = false,
    int limit = 6,
  }) {
    return getSuggestedImagesForText(
      product.name,
      category: product.category,
      brand: product.brand,
      category3Levels: product.category3Levels,
      isCombo: product.isCombo,
      furnitureOnly: furnitureOnly,
      limit: limit,
    );
  }

  /// Get list of top suggested images from input texts
  static List<SampleImageMatch> getSuggestedImagesForText(
    String name, {
    String? category,
    String? brand,
    String? category3Levels,
    bool isCombo = false,
    bool furnitureOnly = false,
    int limit = 6,
  }) {
    final matches = <SampleImageMatch>[];

    // 1. Search in primary 100% Furniture & Woodcraft catalog
    for (final cat in catalog) {
      final score = _calculateScore(
        cat: cat,
        name: name,
        category: category ?? '',
        brand: brand ?? '',
        category3Levels: category3Levels ?? '',
        isCombo: isCombo,
      );
      if (score > 0) {
        matches.add(SampleImageMatch(category: cat, score: score));
      }
    }

    // 2. If no match in furniture, fallback to legacy catalog for test backwards compatibility
    if (matches.isEmpty && !furnitureOnly) {
      for (final cat in _legacyCatalog) {
        final score = _calculateScore(
          cat: cat,
          name: name,
          category: category ?? '',
          brand: brand ?? '',
          category3Levels: category3Levels ?? '',
          isCombo: isCombo,
        );
        if (score > 0) {
          matches.add(SampleImageMatch(category: cat, score: score));
        }
      }
    }

    matches.sort((a, b) => b.score.compareTo(a.score));

    if (matches.isEmpty) {
      return const [];
    }

    return matches.take(limit).toList();
  }

  /// Map product to a high-quality relevant online image URL based on its name and category
  static String getSampleImageUrl(Product product,
      {bool furnitureOnly = false}) {
    return getSampleImageUrlForText(
      product.name,
      category: product.category,
      brand: product.brand,
      category3Levels: product.category3Levels,
      isCombo: product.isCombo,
      furnitureOnly: furnitureOnly,
    );
  }

  /// Map raw input values to a high-quality sample image URL
  static String getSampleImageUrlForText(
    String name, {
    String? category,
    String? brand,
    String? category3Levels,
    bool isCombo = false,
    bool furnitureOnly = false,
  }) {
    final matches = getSuggestedImagesForText(
      name,
      category: category,
      brand: brand,
      category3Levels: category3Levels,
      isCombo: isCombo,
      furnitureOnly: furnitureOnly,
      limit: 1,
    );

    if (matches.isNotEmpty && matches.first.score > 0) {
      return matches.first.imageUrl;
    }

    return '';
  }
}
